[package]
name = "mlp"
version = "0.1.0"
edition = "2021"

[lib]
name = "mlp"
crate-type = ["cdylib"]

[dependencies]
rand = "0.9.0-alpha.1"
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
